### ISSUE TITLE
What is the "load" config value in a periodic event?

### ISSUE THREAD

**Issue by js1972** [cap-js-community/event-queue#71]
I'd like to test this project with a periodic event that will do some data sync/caching with a remote system. I can't see from the doco exactly what the load config parameter does?

There is a sample cap app in the repo where it is set to "40".

<img width="669" alt="image" src="https://github.com/cap-js-community/event-queue/assets/1317161/21fc7c56-c3dd-4b26-a25b-8883f53f1bb2">

**Comment by soccermax** [comment]
The load parameter serves the function of regulating the number of concurrent processes permitted per app-instance. The maximum load for each app-instance is 100.

Consider the following scenario:
- There are three events (irrespective of whether they are periodic or ad-hoc events).
- Event A has a specified load of 40.
- Event B has a specified load of 50.
- Event C has a specified load of 20.

At the start, when the server initiates the event queue, the load is 0. If Event A is triggered, the load becomes 40. The remaining load that the app-instance can handle is 60. Therefore, Event B can also be started, which brings the total load to 90. At this point, Event C must wait until either Event A or B is completed because the current load is already at 90. However, if your app is running on Cloud Foundry with more than one instance, another instance with available capacity would process Event C.

I hope this answers your question. I will add such an example to the documentation to make this concept clearer.

**Comment by js1972** [comment]
Ok, interesting. So it's more a way to block too much load on your app's instance. 
So if you only want to have one event to be processed at a time you'd set the load property to 100. 

In my case with a scheduled event I'm not sure that it matters - unless I get into an ugly situation where the processing time of the event handler is longer w the time between events.

**Comment by soccermax** [comment]
> Ok, interesting. So it's more a way to block too much load on your app's instance.

Exactly, in our project, we process almost a million events every day. In such use cases, it's crucial to avoid CPU/Memory spikes. And in our project, some processes consume much more memory/CPU than others. That's why we want to differentiate.

> So if you only want to have one event to be processed at a time you'd set the load property to 100.

Correct, in a single tenant application (let me explain this in conjunction with the next question)

> In my case with a scheduled event I'm not sure that it matters - unless I get into an ugly situation where the processing time of the event handler is longer w the time between events.

This would still be relevant even if you only have one event but multiple tenants. Imagine you have a multi-tenancy app with 100 tenants. In such cases, you'd also want to control the parallelization in your application.
