### ISSUE TITLE
What does a log error for Waiting time in worker queue ( diffMs> 37782 } mean?

### ISSUE THREAD

**Issue by js1972** [cap-js-community/event-queue#82]
I am using an event queue for a scheduled execution. When testing with a 10 min period I encounter the following log error. Note that the event handler code runs successfully and commits my db changes.

![image](https://github.com/cap-js-community/event-queue/assets/1317161/5a4d4921-bbdc-4439-b5e2-dcccb711c17b)

**Comment by soccermax** [comment]
The waiting time for the worker signifies that the event-queue was checked for any pending tasks, but the maximum load for the app-instance had already been reached. Consequently, the next run had to wait for 37 seconds before it could be executed. 

To mitigate this, you could consider increasing the `runInterval` parameter. This would result in the event-queue checking less frequently for tasks. Another approach could be to decrease the load of the event to 50%, thereby providing the event-queue with an opportunity to ascertain whether a subsequent run is due or not.

**Comment by js1972** [comment]
Maybe I don't fully understand the load parameter. 

My config has the period set to 10mins. 
The event handler takes about 1 minute to process (while using test data - in real life it could be a few mins).

So when the second event is fired why would the system think the load was already used up?

I do have the load set to 100 so that only one event can process at a time but that should be fine with the above timings?

**Comment by soccermax** [comment]
You do understand the load parameter correctly. Here's what's happening:
- Your event is being executed (which takes one minute).
- The event queue checks every X minutes (the default is 5 minutes) to see if something needs to be scheduled.
- If the event queue checks at the same time your event is being executed, the log you're seeing is generated. This happens because the system can only check if the load capacity has not been reached. Does that make sense?

In your case, this isn't an issue at all. However, it does result in an error log, which isn't ideal. If you want to avoid this, you can increase the `runInterval`. This will reduce the frequency at which the event queue checks for events that need to be scheduled.

**Comment by js1972** [comment]
Ok so it's the "runner" that matters for the load parameter by the sounds of it. 

So if by chance in my testing the running checks for events every 5 min and it happens to be when an event is already executing I get the error message because it's blown the "load". 

If I increase the run interval - theres still a chance of getting there though right? 

Maybe a load value of 100 is not suitable here. Let me test it at a lower value like 10. 
I can't see there even being a real world case where the event processor would be running - 2 at a time. 
My period will be many hours (likely 24hrs) and event handler runtime will be a few minutes.

**Comment by soccermax** [comment]
Please reopen if you have any further questions
